// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AiSearchBatteryEp } from '../src/api/aiSearchBattery';
import type { default as _AiSearchEnergyPlanEp } from '../src/api/aiSearchEnergyPlan';
import type { default as _AiSearchSolarPanelEp } from '../src/api/aiSearchSolarPanel';
import type { default as _ApplyBatteryUpdatesEp } from '../src/api/applyBatteryUpdates';
import type { default as _ApplyUrlChangesEp } from '../src/api/applyUrlChanges';
import type { default as _CheckBatteryUpdatesEp } from '../src/api/checkBatteryUpdates';
import type { default as _CheckSingleBatteryUpdateEp } from '../src/api/checkSingleBatteryUpdate';
import type { default as _DeleteBatteryEp } from '../src/api/deleteBattery';
import type { default as _DeleteBatteryReviewEp } from '../src/api/deleteBatteryReview';
import type { default as _DeleteCapacityOptionEp } from '../src/api/deleteCapacityOption';
import type { default as _DeleteEnergyPlanEp } from '../src/api/deleteEnergyPlan';
import type { default as _DeleteInspectorEp } from '../src/api/deleteInspector';
import type { default as _DeleteInstallPhotoEp } from '../src/api/deleteInstallPhoto';
import type { default as _DeleteInstallerEp } from '../src/api/deleteInstaller';
import type { default as _DeleteInstallerAccreditationEp } from '../src/api/deleteInstallerAccreditation';
import type { default as _DeleteInstallerPricingEp } from '../src/api/deleteInstallerPricing';
import type { default as _DeleteInstallerReviewEp } from '../src/api/deleteInstallerReview';
import type { default as _DeletePlanCompatibilityEp } from '../src/api/deletePlanCompatibility';
import type { default as _DeleteSolarPanelEp } from '../src/api/deleteSolarPanel';
import type { default as _DiscoverMarketBatteriesEp } from '../src/api/discoverMarketBatteries';
import type { default as _DiscoverMarketPlansEp } from '../src/api/discoverMarketPlans';
import type { default as _ExtractFromUrlEp } from '../src/api/extractFromUrl';
import type { default as _FetchBatteryReviewsEp } from '../src/api/fetchBatteryReviews';
import type { default as _GetBatteriesForCalculatorEp } from '../src/api/getBatteriesForCalculator';
import type { default as _GetBatteryDetailEp } from '../src/api/getBatteryDetail';
import type { default as _GetBatteryInstallersEp } from '../src/api/getBatteryInstallers';
import type { default as _GetInstallerBatteryPricingEp } from '../src/api/getInstallerBatteryPricing';
import type { default as _GetSolarPanelDetailEp } from '../src/api/getSolarPanelDetail';
import type { default as _ListAllCapacityOptionsEp } from '../src/api/listAllCapacityOptions';
import type { default as _ListBatteriesEp } from '../src/api/listBatteries';
import type { default as _ListBatteriesWithPricingEp } from '../src/api/listBatteriesWithPricing';
import type { default as _ListBatteryReviewsEp } from '../src/api/listBatteryReviews';
import type { default as _ListCapacityOptionsEp } from '../src/api/listCapacityOptions';
import type { default as _ListEnergyPlansEp } from '../src/api/listEnergyPlans';
import type { default as _ListInspectorsEp } from '../src/api/listInspectors';
import type { default as _ListInstallPhotosEp } from '../src/api/listInstallPhotos';
import type { default as _ListInstallerAccreditationsEp } from '../src/api/listInstallerAccreditations';
import type { default as _ListInstallerPricingEp } from '../src/api/listInstallerPricing';
import type { default as _ListInstallerReviewsEp } from '../src/api/listInstallerReviews';
import type { default as _ListInstallersEp } from '../src/api/listInstallers';
import type { default as _ListPlanCompatibilityEp } from '../src/api/listPlanCompatibility';
import type { default as _ListSolarPanelsEp } from '../src/api/listSolarPanels';
import type { default as _SaveBatteryEp } from '../src/api/saveBattery';
import type { default as _SaveCapacityOptionEp } from '../src/api/saveCapacityOption';
import type { default as _SaveEnergyPlanEp } from '../src/api/saveEnergyPlan';
import type { default as _SaveInspectorEp } from '../src/api/saveInspector';
import type { default as _SaveInstallPhotoEp } from '../src/api/saveInstallPhoto';
import type { default as _SaveInstallerEp } from '../src/api/saveInstaller';
import type { default as _SaveInstallerAccreditationEp } from '../src/api/saveInstallerAccreditation';
import type { default as _SaveInstallerPricingEp } from '../src/api/saveInstallerPricing';
import type { default as _SaveInstallerReviewEp } from '../src/api/saveInstallerReview';
import type { default as _SavePlanCompatibilityEp } from '../src/api/savePlanCompatibility';
import type { default as _SavePlanFromBatterySearchEp } from '../src/api/savePlanFromBatterySearch';
import type { default as _SaveSelectedReviewsEp } from '../src/api/saveSelectedReviews';
import type { default as _SaveSolarPanelEp } from '../src/api/saveSolarPanel';
import type { default as _SeedBatteriesEp } from '../src/api/seedBatteries';
import type { default as _UpdateBatteryPlansEp } from '../src/api/updateBatteryPlans';

type _AiSearchBatteryCfg = typeof _AiSearchBatteryEp;
export type AiSearchBatteryInputType = NonNullable<_AiSearchBatteryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiSearchBatteryCfg['execute']>[0]['input'];
export type AiSearchBatteryOutputType = Awaited<ReturnType<_AiSearchBatteryCfg['execute']>>;
export const aiSearchBattery = createCaller<AiSearchBatteryInputType, AiSearchBatteryOutputType>('aiSearchBattery');

type _AiSearchEnergyPlanCfg = typeof _AiSearchEnergyPlanEp;
export type AiSearchEnergyPlanInputType = NonNullable<_AiSearchEnergyPlanCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiSearchEnergyPlanCfg['execute']>[0]['input'];
export type AiSearchEnergyPlanOutputType = Awaited<ReturnType<_AiSearchEnergyPlanCfg['execute']>>;
export const aiSearchEnergyPlan = createCaller<AiSearchEnergyPlanInputType, AiSearchEnergyPlanOutputType>('aiSearchEnergyPlan');

type _AiSearchSolarPanelCfg = typeof _AiSearchSolarPanelEp;
export type AiSearchSolarPanelInputType = NonNullable<_AiSearchSolarPanelCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiSearchSolarPanelCfg['execute']>[0]['input'];
export type AiSearchSolarPanelOutputType = Awaited<ReturnType<_AiSearchSolarPanelCfg['execute']>>;
export const aiSearchSolarPanel = createCaller<AiSearchSolarPanelInputType, AiSearchSolarPanelOutputType>('aiSearchSolarPanel');

type _ApplyBatteryUpdatesCfg = typeof _ApplyBatteryUpdatesEp;
export type ApplyBatteryUpdatesInputType = NonNullable<_ApplyBatteryUpdatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ApplyBatteryUpdatesCfg['execute']>[0]['input'];
export type ApplyBatteryUpdatesOutputType = Awaited<ReturnType<_ApplyBatteryUpdatesCfg['execute']>>;
export const applyBatteryUpdates = createCaller<ApplyBatteryUpdatesInputType, ApplyBatteryUpdatesOutputType>('applyBatteryUpdates');

type _ApplyUrlChangesCfg = typeof _ApplyUrlChangesEp;
export type ApplyUrlChangesInputType = NonNullable<_ApplyUrlChangesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ApplyUrlChangesCfg['execute']>[0]['input'];
export type ApplyUrlChangesOutputType = Awaited<ReturnType<_ApplyUrlChangesCfg['execute']>>;
export const applyUrlChanges = createCaller<ApplyUrlChangesInputType, ApplyUrlChangesOutputType>('applyUrlChanges');

type _CheckBatteryUpdatesCfg = typeof _CheckBatteryUpdatesEp;
export type CheckBatteryUpdatesInputType = NonNullable<_CheckBatteryUpdatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CheckBatteryUpdatesCfg['execute']>[0]['input'];
export type CheckBatteryUpdatesOutputType = Awaited<ReturnType<_CheckBatteryUpdatesCfg['execute']>>;
export const checkBatteryUpdates = createCaller<CheckBatteryUpdatesInputType, CheckBatteryUpdatesOutputType>('checkBatteryUpdates');

type _CheckSingleBatteryUpdateCfg = typeof _CheckSingleBatteryUpdateEp;
export type CheckSingleBatteryUpdateInputType = NonNullable<_CheckSingleBatteryUpdateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CheckSingleBatteryUpdateCfg['execute']>[0]['input'];
export type CheckSingleBatteryUpdateOutputType = Awaited<ReturnType<_CheckSingleBatteryUpdateCfg['execute']>>;
export const checkSingleBatteryUpdate = createCaller<CheckSingleBatteryUpdateInputType, CheckSingleBatteryUpdateOutputType>('checkSingleBatteryUpdate');

type _DeleteBatteryCfg = typeof _DeleteBatteryEp;
export type DeleteBatteryInputType = NonNullable<_DeleteBatteryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteBatteryCfg['execute']>[0]['input'];
export type DeleteBatteryOutputType = Awaited<ReturnType<_DeleteBatteryCfg['execute']>>;
export const deleteBattery = createCaller<DeleteBatteryInputType, DeleteBatteryOutputType>('deleteBattery');

type _DeleteBatteryReviewCfg = typeof _DeleteBatteryReviewEp;
export type DeleteBatteryReviewInputType = NonNullable<_DeleteBatteryReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteBatteryReviewCfg['execute']>[0]['input'];
export type DeleteBatteryReviewOutputType = Awaited<ReturnType<_DeleteBatteryReviewCfg['execute']>>;
export const deleteBatteryReview = createCaller<DeleteBatteryReviewInputType, DeleteBatteryReviewOutputType>('deleteBatteryReview');

type _DeleteCapacityOptionCfg = typeof _DeleteCapacityOptionEp;
export type DeleteCapacityOptionInputType = NonNullable<_DeleteCapacityOptionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteCapacityOptionCfg['execute']>[0]['input'];
export type DeleteCapacityOptionOutputType = Awaited<ReturnType<_DeleteCapacityOptionCfg['execute']>>;
export const deleteCapacityOption = createCaller<DeleteCapacityOptionInputType, DeleteCapacityOptionOutputType>('deleteCapacityOption');

type _DeleteEnergyPlanCfg = typeof _DeleteEnergyPlanEp;
export type DeleteEnergyPlanInputType = NonNullable<_DeleteEnergyPlanCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteEnergyPlanCfg['execute']>[0]['input'];
export type DeleteEnergyPlanOutputType = Awaited<ReturnType<_DeleteEnergyPlanCfg['execute']>>;
export const deleteEnergyPlan = createCaller<DeleteEnergyPlanInputType, DeleteEnergyPlanOutputType>('deleteEnergyPlan');

type _DeleteInspectorCfg = typeof _DeleteInspectorEp;
export type DeleteInspectorInputType = NonNullable<_DeleteInspectorCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteInspectorCfg['execute']>[0]['input'];
export type DeleteInspectorOutputType = Awaited<ReturnType<_DeleteInspectorCfg['execute']>>;
export const deleteInspector = createCaller<DeleteInspectorInputType, DeleteInspectorOutputType>('deleteInspector');

type _DeleteInstallPhotoCfg = typeof _DeleteInstallPhotoEp;
export type DeleteInstallPhotoInputType = NonNullable<_DeleteInstallPhotoCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteInstallPhotoCfg['execute']>[0]['input'];
export type DeleteInstallPhotoOutputType = Awaited<ReturnType<_DeleteInstallPhotoCfg['execute']>>;
export const deleteInstallPhoto = createCaller<DeleteInstallPhotoInputType, DeleteInstallPhotoOutputType>('deleteInstallPhoto');

type _DeleteInstallerCfg = typeof _DeleteInstallerEp;
export type DeleteInstallerInputType = NonNullable<_DeleteInstallerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteInstallerCfg['execute']>[0]['input'];
export type DeleteInstallerOutputType = Awaited<ReturnType<_DeleteInstallerCfg['execute']>>;
export const deleteInstaller = createCaller<DeleteInstallerInputType, DeleteInstallerOutputType>('deleteInstaller');

type _DeleteInstallerAccreditationCfg = typeof _DeleteInstallerAccreditationEp;
export type DeleteInstallerAccreditationInputType = NonNullable<_DeleteInstallerAccreditationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteInstallerAccreditationCfg['execute']>[0]['input'];
export type DeleteInstallerAccreditationOutputType = Awaited<ReturnType<_DeleteInstallerAccreditationCfg['execute']>>;
export const deleteInstallerAccreditation = createCaller<DeleteInstallerAccreditationInputType, DeleteInstallerAccreditationOutputType>('deleteInstallerAccreditation');

type _DeleteInstallerPricingCfg = typeof _DeleteInstallerPricingEp;
export type DeleteInstallerPricingInputType = NonNullable<_DeleteInstallerPricingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteInstallerPricingCfg['execute']>[0]['input'];
export type DeleteInstallerPricingOutputType = Awaited<ReturnType<_DeleteInstallerPricingCfg['execute']>>;
export const deleteInstallerPricing = createCaller<DeleteInstallerPricingInputType, DeleteInstallerPricingOutputType>('deleteInstallerPricing');

type _DeleteInstallerReviewCfg = typeof _DeleteInstallerReviewEp;
export type DeleteInstallerReviewInputType = NonNullable<_DeleteInstallerReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteInstallerReviewCfg['execute']>[0]['input'];
export type DeleteInstallerReviewOutputType = Awaited<ReturnType<_DeleteInstallerReviewCfg['execute']>>;
export const deleteInstallerReview = createCaller<DeleteInstallerReviewInputType, DeleteInstallerReviewOutputType>('deleteInstallerReview');

type _DeletePlanCompatibilityCfg = typeof _DeletePlanCompatibilityEp;
export type DeletePlanCompatibilityInputType = NonNullable<_DeletePlanCompatibilityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeletePlanCompatibilityCfg['execute']>[0]['input'];
export type DeletePlanCompatibilityOutputType = Awaited<ReturnType<_DeletePlanCompatibilityCfg['execute']>>;
export const deletePlanCompatibility = createCaller<DeletePlanCompatibilityInputType, DeletePlanCompatibilityOutputType>('deletePlanCompatibility');

type _DeleteSolarPanelCfg = typeof _DeleteSolarPanelEp;
export type DeleteSolarPanelInputType = NonNullable<_DeleteSolarPanelCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteSolarPanelCfg['execute']>[0]['input'];
export type DeleteSolarPanelOutputType = Awaited<ReturnType<_DeleteSolarPanelCfg['execute']>>;
export const deleteSolarPanel = createCaller<DeleteSolarPanelInputType, DeleteSolarPanelOutputType>('deleteSolarPanel');

type _DiscoverMarketBatteriesCfg = typeof _DiscoverMarketBatteriesEp;
export type DiscoverMarketBatteriesInputType = NonNullable<_DiscoverMarketBatteriesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DiscoverMarketBatteriesCfg['execute']>[0]['input'];
export type DiscoverMarketBatteriesOutputType = Awaited<ReturnType<_DiscoverMarketBatteriesCfg['execute']>>;
export const discoverMarketBatteries = createCaller<DiscoverMarketBatteriesInputType, DiscoverMarketBatteriesOutputType>('discoverMarketBatteries');

type _DiscoverMarketPlansCfg = typeof _DiscoverMarketPlansEp;
export type DiscoverMarketPlansInputType = NonNullable<_DiscoverMarketPlansCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DiscoverMarketPlansCfg['execute']>[0]['input'];
export type DiscoverMarketPlansOutputType = Awaited<ReturnType<_DiscoverMarketPlansCfg['execute']>>;
export const discoverMarketPlans = createCaller<DiscoverMarketPlansInputType, DiscoverMarketPlansOutputType>('discoverMarketPlans');

type _ExtractFromUrlCfg = typeof _ExtractFromUrlEp;
export type ExtractFromUrlInputType = NonNullable<_ExtractFromUrlCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExtractFromUrlCfg['execute']>[0]['input'];
export type ExtractFromUrlOutputType = Awaited<ReturnType<_ExtractFromUrlCfg['execute']>>;
export const extractFromUrl = createCaller<ExtractFromUrlInputType, ExtractFromUrlOutputType>('extractFromUrl');

type _FetchBatteryReviewsCfg = typeof _FetchBatteryReviewsEp;
export type FetchBatteryReviewsInputType = NonNullable<_FetchBatteryReviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_FetchBatteryReviewsCfg['execute']>[0]['input'];
export type FetchBatteryReviewsOutputType = Awaited<ReturnType<_FetchBatteryReviewsCfg['execute']>>;
export const fetchBatteryReviews = createCaller<FetchBatteryReviewsInputType, FetchBatteryReviewsOutputType>('fetchBatteryReviews');

type _GetBatteriesForCalculatorCfg = typeof _GetBatteriesForCalculatorEp;
export type GetBatteriesForCalculatorInputType = NonNullable<_GetBatteriesForCalculatorCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBatteriesForCalculatorCfg['execute']>[0]['input'];
export type GetBatteriesForCalculatorOutputType = Awaited<ReturnType<_GetBatteriesForCalculatorCfg['execute']>>;
export const getBatteriesForCalculator = createCaller<GetBatteriesForCalculatorInputType, GetBatteriesForCalculatorOutputType>('getBatteriesForCalculator');

type _GetBatteryDetailCfg = typeof _GetBatteryDetailEp;
export type GetBatteryDetailInputType = NonNullable<_GetBatteryDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBatteryDetailCfg['execute']>[0]['input'];
export type GetBatteryDetailOutputType = Awaited<ReturnType<_GetBatteryDetailCfg['execute']>>;
export const getBatteryDetail = createCaller<GetBatteryDetailInputType, GetBatteryDetailOutputType>('getBatteryDetail');

type _GetBatteryInstallersCfg = typeof _GetBatteryInstallersEp;
export type GetBatteryInstallersInputType = NonNullable<_GetBatteryInstallersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBatteryInstallersCfg['execute']>[0]['input'];
export type GetBatteryInstallersOutputType = Awaited<ReturnType<_GetBatteryInstallersCfg['execute']>>;
export const getBatteryInstallers = createCaller<GetBatteryInstallersInputType, GetBatteryInstallersOutputType>('getBatteryInstallers');

type _GetInstallerBatteryPricingCfg = typeof _GetInstallerBatteryPricingEp;
export type GetInstallerBatteryPricingInputType = NonNullable<_GetInstallerBatteryPricingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetInstallerBatteryPricingCfg['execute']>[0]['input'];
export type GetInstallerBatteryPricingOutputType = Awaited<ReturnType<_GetInstallerBatteryPricingCfg['execute']>>;
export const getInstallerBatteryPricing = createCaller<GetInstallerBatteryPricingInputType, GetInstallerBatteryPricingOutputType>('getInstallerBatteryPricing');

type _GetSolarPanelDetailCfg = typeof _GetSolarPanelDetailEp;
export type GetSolarPanelDetailInputType = NonNullable<_GetSolarPanelDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSolarPanelDetailCfg['execute']>[0]['input'];
export type GetSolarPanelDetailOutputType = Awaited<ReturnType<_GetSolarPanelDetailCfg['execute']>>;
export const getSolarPanelDetail = createCaller<GetSolarPanelDetailInputType, GetSolarPanelDetailOutputType>('getSolarPanelDetail');

type _ListAllCapacityOptionsCfg = typeof _ListAllCapacityOptionsEp;
export type ListAllCapacityOptionsInputType = NonNullable<_ListAllCapacityOptionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListAllCapacityOptionsCfg['execute']>[0]['input'];
export type ListAllCapacityOptionsOutputType = Awaited<ReturnType<_ListAllCapacityOptionsCfg['execute']>>;
export const listAllCapacityOptions = createCaller<ListAllCapacityOptionsInputType, ListAllCapacityOptionsOutputType>('listAllCapacityOptions');

type _ListBatteriesCfg = typeof _ListBatteriesEp;
export type ListBatteriesInputType = NonNullable<_ListBatteriesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListBatteriesCfg['execute']>[0]['input'];
export type ListBatteriesOutputType = Awaited<ReturnType<_ListBatteriesCfg['execute']>>;
export const listBatteries = createCaller<ListBatteriesInputType, ListBatteriesOutputType>('listBatteries');

type _ListBatteriesWithPricingCfg = typeof _ListBatteriesWithPricingEp;
export type ListBatteriesWithPricingInputType = NonNullable<_ListBatteriesWithPricingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListBatteriesWithPricingCfg['execute']>[0]['input'];
export type ListBatteriesWithPricingOutputType = Awaited<ReturnType<_ListBatteriesWithPricingCfg['execute']>>;
export const listBatteriesWithPricing = createCaller<ListBatteriesWithPricingInputType, ListBatteriesWithPricingOutputType>('listBatteriesWithPricing');

type _ListBatteryReviewsCfg = typeof _ListBatteryReviewsEp;
export type ListBatteryReviewsInputType = NonNullable<_ListBatteryReviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListBatteryReviewsCfg['execute']>[0]['input'];
export type ListBatteryReviewsOutputType = Awaited<ReturnType<_ListBatteryReviewsCfg['execute']>>;
export const listBatteryReviews = createCaller<ListBatteryReviewsInputType, ListBatteryReviewsOutputType>('listBatteryReviews');

type _ListCapacityOptionsCfg = typeof _ListCapacityOptionsEp;
export type ListCapacityOptionsInputType = NonNullable<_ListCapacityOptionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListCapacityOptionsCfg['execute']>[0]['input'];
export type ListCapacityOptionsOutputType = Awaited<ReturnType<_ListCapacityOptionsCfg['execute']>>;
export const listCapacityOptions = createCaller<ListCapacityOptionsInputType, ListCapacityOptionsOutputType>('listCapacityOptions');

type _ListEnergyPlansCfg = typeof _ListEnergyPlansEp;
export type ListEnergyPlansInputType = NonNullable<_ListEnergyPlansCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListEnergyPlansCfg['execute']>[0]['input'];
export type ListEnergyPlansOutputType = Awaited<ReturnType<_ListEnergyPlansCfg['execute']>>;
export const listEnergyPlans = createCaller<ListEnergyPlansInputType, ListEnergyPlansOutputType>('listEnergyPlans');

type _ListInspectorsCfg = typeof _ListInspectorsEp;
export type ListInspectorsInputType = NonNullable<_ListInspectorsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInspectorsCfg['execute']>[0]['input'];
export type ListInspectorsOutputType = Awaited<ReturnType<_ListInspectorsCfg['execute']>>;
export const listInspectors = createCaller<ListInspectorsInputType, ListInspectorsOutputType>('listInspectors');

type _ListInstallPhotosCfg = typeof _ListInstallPhotosEp;
export type ListInstallPhotosInputType = NonNullable<_ListInstallPhotosCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInstallPhotosCfg['execute']>[0]['input'];
export type ListInstallPhotosOutputType = Awaited<ReturnType<_ListInstallPhotosCfg['execute']>>;
export const listInstallPhotos = createCaller<ListInstallPhotosInputType, ListInstallPhotosOutputType>('listInstallPhotos');

type _ListInstallerAccreditationsCfg = typeof _ListInstallerAccreditationsEp;
export type ListInstallerAccreditationsInputType = NonNullable<_ListInstallerAccreditationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInstallerAccreditationsCfg['execute']>[0]['input'];
export type ListInstallerAccreditationsOutputType = Awaited<ReturnType<_ListInstallerAccreditationsCfg['execute']>>;
export const listInstallerAccreditations = createCaller<ListInstallerAccreditationsInputType, ListInstallerAccreditationsOutputType>('listInstallerAccreditations');

type _ListInstallerPricingCfg = typeof _ListInstallerPricingEp;
export type ListInstallerPricingInputType = NonNullable<_ListInstallerPricingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInstallerPricingCfg['execute']>[0]['input'];
export type ListInstallerPricingOutputType = Awaited<ReturnType<_ListInstallerPricingCfg['execute']>>;
export const listInstallerPricing = createCaller<ListInstallerPricingInputType, ListInstallerPricingOutputType>('listInstallerPricing');

type _ListInstallerReviewsCfg = typeof _ListInstallerReviewsEp;
export type ListInstallerReviewsInputType = NonNullable<_ListInstallerReviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInstallerReviewsCfg['execute']>[0]['input'];
export type ListInstallerReviewsOutputType = Awaited<ReturnType<_ListInstallerReviewsCfg['execute']>>;
export const listInstallerReviews = createCaller<ListInstallerReviewsInputType, ListInstallerReviewsOutputType>('listInstallerReviews');

type _ListInstallersCfg = typeof _ListInstallersEp;
export type ListInstallersInputType = NonNullable<_ListInstallersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInstallersCfg['execute']>[0]['input'];
export type ListInstallersOutputType = Awaited<ReturnType<_ListInstallersCfg['execute']>>;
export const listInstallers = createCaller<ListInstallersInputType, ListInstallersOutputType>('listInstallers');

type _ListPlanCompatibilityCfg = typeof _ListPlanCompatibilityEp;
export type ListPlanCompatibilityInputType = NonNullable<_ListPlanCompatibilityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPlanCompatibilityCfg['execute']>[0]['input'];
export type ListPlanCompatibilityOutputType = Awaited<ReturnType<_ListPlanCompatibilityCfg['execute']>>;
export const listPlanCompatibility = createCaller<ListPlanCompatibilityInputType, ListPlanCompatibilityOutputType>('listPlanCompatibility');

type _ListSolarPanelsCfg = typeof _ListSolarPanelsEp;
export type ListSolarPanelsInputType = NonNullable<_ListSolarPanelsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSolarPanelsCfg['execute']>[0]['input'];
export type ListSolarPanelsOutputType = Awaited<ReturnType<_ListSolarPanelsCfg['execute']>>;
export const listSolarPanels = createCaller<ListSolarPanelsInputType, ListSolarPanelsOutputType>('listSolarPanels');

type _SaveBatteryCfg = typeof _SaveBatteryEp;
export type SaveBatteryInputType = NonNullable<_SaveBatteryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveBatteryCfg['execute']>[0]['input'];
export type SaveBatteryOutputType = Awaited<ReturnType<_SaveBatteryCfg['execute']>>;
export const saveBattery = createCaller<SaveBatteryInputType, SaveBatteryOutputType>('saveBattery');

type _SaveCapacityOptionCfg = typeof _SaveCapacityOptionEp;
export type SaveCapacityOptionInputType = NonNullable<_SaveCapacityOptionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveCapacityOptionCfg['execute']>[0]['input'];
export type SaveCapacityOptionOutputType = Awaited<ReturnType<_SaveCapacityOptionCfg['execute']>>;
export const saveCapacityOption = createCaller<SaveCapacityOptionInputType, SaveCapacityOptionOutputType>('saveCapacityOption');

type _SaveEnergyPlanCfg = typeof _SaveEnergyPlanEp;
export type SaveEnergyPlanInputType = NonNullable<_SaveEnergyPlanCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveEnergyPlanCfg['execute']>[0]['input'];
export type SaveEnergyPlanOutputType = Awaited<ReturnType<_SaveEnergyPlanCfg['execute']>>;
export const saveEnergyPlan = createCaller<SaveEnergyPlanInputType, SaveEnergyPlanOutputType>('saveEnergyPlan');

type _SaveInspectorCfg = typeof _SaveInspectorEp;
export type SaveInspectorInputType = NonNullable<_SaveInspectorCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveInspectorCfg['execute']>[0]['input'];
export type SaveInspectorOutputType = Awaited<ReturnType<_SaveInspectorCfg['execute']>>;
export const saveInspector = createCaller<SaveInspectorInputType, SaveInspectorOutputType>('saveInspector');

type _SaveInstallPhotoCfg = typeof _SaveInstallPhotoEp;
export type SaveInstallPhotoInputType = NonNullable<_SaveInstallPhotoCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveInstallPhotoCfg['execute']>[0]['input'];
export type SaveInstallPhotoOutputType = Awaited<ReturnType<_SaveInstallPhotoCfg['execute']>>;
export const saveInstallPhoto = createCaller<SaveInstallPhotoInputType, SaveInstallPhotoOutputType>('saveInstallPhoto');

type _SaveInstallerCfg = typeof _SaveInstallerEp;
export type SaveInstallerInputType = NonNullable<_SaveInstallerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveInstallerCfg['execute']>[0]['input'];
export type SaveInstallerOutputType = Awaited<ReturnType<_SaveInstallerCfg['execute']>>;
export const saveInstaller = createCaller<SaveInstallerInputType, SaveInstallerOutputType>('saveInstaller');

type _SaveInstallerAccreditationCfg = typeof _SaveInstallerAccreditationEp;
export type SaveInstallerAccreditationInputType = NonNullable<_SaveInstallerAccreditationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveInstallerAccreditationCfg['execute']>[0]['input'];
export type SaveInstallerAccreditationOutputType = Awaited<ReturnType<_SaveInstallerAccreditationCfg['execute']>>;
export const saveInstallerAccreditation = createCaller<SaveInstallerAccreditationInputType, SaveInstallerAccreditationOutputType>('saveInstallerAccreditation');

type _SaveInstallerPricingCfg = typeof _SaveInstallerPricingEp;
export type SaveInstallerPricingInputType = NonNullable<_SaveInstallerPricingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveInstallerPricingCfg['execute']>[0]['input'];
export type SaveInstallerPricingOutputType = Awaited<ReturnType<_SaveInstallerPricingCfg['execute']>>;
export const saveInstallerPricing = createCaller<SaveInstallerPricingInputType, SaveInstallerPricingOutputType>('saveInstallerPricing');

type _SaveInstallerReviewCfg = typeof _SaveInstallerReviewEp;
export type SaveInstallerReviewInputType = NonNullable<_SaveInstallerReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveInstallerReviewCfg['execute']>[0]['input'];
export type SaveInstallerReviewOutputType = Awaited<ReturnType<_SaveInstallerReviewCfg['execute']>>;
export const saveInstallerReview = createCaller<SaveInstallerReviewInputType, SaveInstallerReviewOutputType>('saveInstallerReview');

type _SavePlanCompatibilityCfg = typeof _SavePlanCompatibilityEp;
export type SavePlanCompatibilityInputType = NonNullable<_SavePlanCompatibilityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePlanCompatibilityCfg['execute']>[0]['input'];
export type SavePlanCompatibilityOutputType = Awaited<ReturnType<_SavePlanCompatibilityCfg['execute']>>;
export const savePlanCompatibility = createCaller<SavePlanCompatibilityInputType, SavePlanCompatibilityOutputType>('savePlanCompatibility');

type _SavePlanFromBatterySearchCfg = typeof _SavePlanFromBatterySearchEp;
export type SavePlanFromBatterySearchInputType = NonNullable<_SavePlanFromBatterySearchCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePlanFromBatterySearchCfg['execute']>[0]['input'];
export type SavePlanFromBatterySearchOutputType = Awaited<ReturnType<_SavePlanFromBatterySearchCfg['execute']>>;
export const savePlanFromBatterySearch = createCaller<SavePlanFromBatterySearchInputType, SavePlanFromBatterySearchOutputType>('savePlanFromBatterySearch');

type _SaveSelectedReviewsCfg = typeof _SaveSelectedReviewsEp;
export type SaveSelectedReviewsInputType = NonNullable<_SaveSelectedReviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSelectedReviewsCfg['execute']>[0]['input'];
export type SaveSelectedReviewsOutputType = Awaited<ReturnType<_SaveSelectedReviewsCfg['execute']>>;
export const saveSelectedReviews = createCaller<SaveSelectedReviewsInputType, SaveSelectedReviewsOutputType>('saveSelectedReviews');

type _SaveSolarPanelCfg = typeof _SaveSolarPanelEp;
export type SaveSolarPanelInputType = NonNullable<_SaveSolarPanelCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSolarPanelCfg['execute']>[0]['input'];
export type SaveSolarPanelOutputType = Awaited<ReturnType<_SaveSolarPanelCfg['execute']>>;
export const saveSolarPanel = createCaller<SaveSolarPanelInputType, SaveSolarPanelOutputType>('saveSolarPanel');

type _SeedBatteriesCfg = typeof _SeedBatteriesEp;
export type SeedBatteriesInputType = NonNullable<_SeedBatteriesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SeedBatteriesCfg['execute']>[0]['input'];
export type SeedBatteriesOutputType = Awaited<ReturnType<_SeedBatteriesCfg['execute']>>;
export const seedBatteries = createCaller<SeedBatteriesInputType, SeedBatteriesOutputType>('seedBatteries');

type _UpdateBatteryPlansCfg = typeof _UpdateBatteryPlansEp;
export type UpdateBatteryPlansInputType = NonNullable<_UpdateBatteryPlansCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateBatteryPlansCfg['execute']>[0]['input'];
export type UpdateBatteryPlansOutputType = Awaited<ReturnType<_UpdateBatteryPlansCfg['execute']>>;
export const updateBatteryPlans = createCaller<UpdateBatteryPlansInputType, UpdateBatteryPlansOutputType>('updateBatteryPlans');


export const api = {
  aiSearchBattery,
  aiSearchEnergyPlan,
  aiSearchSolarPanel,
  applyBatteryUpdates,
  applyUrlChanges,
  checkBatteryUpdates,
  checkSingleBatteryUpdate,
  deleteBattery,
  deleteBatteryReview,
  deleteCapacityOption,
  deleteEnergyPlan,
  deleteInspector,
  deleteInstallPhoto,
  deleteInstaller,
  deleteInstallerAccreditation,
  deleteInstallerPricing,
  deleteInstallerReview,
  deletePlanCompatibility,
  deleteSolarPanel,
  discoverMarketBatteries,
  discoverMarketPlans,
  extractFromUrl,
  fetchBatteryReviews,
  getBatteriesForCalculator,
  getBatteryDetail,
  getBatteryInstallers,
  getInstallerBatteryPricing,
  getSolarPanelDetail,
  listAllCapacityOptions,
  listBatteries,
  listBatteriesWithPricing,
  listBatteryReviews,
  listCapacityOptions,
  listEnergyPlans,
  listInspectors,
  listInstallPhotos,
  listInstallerAccreditations,
  listInstallerPricing,
  listInstallerReviews,
  listInstallers,
  listPlanCompatibility,
  listSolarPanels,
  saveBattery,
  saveCapacityOption,
  saveEnergyPlan,
  saveInspector,
  saveInstallPhoto,
  saveInstaller,
  saveInstallerAccreditation,
  saveInstallerPricing,
  saveInstallerReview,
  savePlanCompatibility,
  savePlanFromBatterySearch,
  saveSelectedReviews,
  saveSolarPanel,
  seedBatteries,
  updateBatteryPlans,
};
